<template>
  <div class="flex-1 flex space-x-4">
    <div class="flex-none w-1/5 mt-14 space-y-3">
      <twice-ui-nav-group>
        <twice-ui-nav-item
          badge-animate
          :badge-count="0"
          badge-color="green"
          label="Abteilungen"
          icon="tabler-sitemap"
          route-name="settings-departments"
          active-route-path="app/settings/settings-departments"
        />
        <twice-ui-nav-item
          badge-animate
          :badge-count="0"
          badge-color="green"
          label="Befähigungen + Fachkunde"
          icon="tabler-user-shield"
          route-name="settings-empowerments"
          active-route-path="app/settings/settings-empowerments"
        />
      </twice-ui-nav-group>
      <twice-ui-nav-group>
        <twice-ui-nav-item
          disabled
          badge-animate
          :badge-count="0"
          badge-color="green"
          label="Ablagen"
          icon="tabler-notebook"
          route-name="settings-instructions-safety-categories"
          active-route-path="app/settings/instructions/safety-instructions-categories"
        />
        <twice-ui-nav-item
          disabled
          badge-animate
          :badge-count="0"
          badge-color="green"
          label="Lagerorte"
          icon="tabler-package"
          route-name="settings-instructions-safety-instructions"
          active-route-path="/app/settings/instructions/safety-instructions"
        />
        <twice-ui-nav-item
          disabled
          badge-animate
          :badge-count="0"
          badge-color="green"
          label="Fahrzeuge"
          icon="tabler-truck"
          route-name="settings-instructions-safety-instructions"
          active-route-path="/app/settings/instructions/safety-instructions"
        />
      </twice-ui-nav-group>
    </div>
    <div class="overflow-hidden flex-1 flex">
      <RouterView />
    </div>
  </div>
</template>
